exclude: ".yarn/|yarn.lock"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: file-contents-sorter
        files: requirements-to-freeze.txt
  - repo: local
    hooks:
      - id: django-check
        name: django check
        entry: venv/bin/python manage.py check
        pass_filenames: false
        language: system
        always_run: true
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"]
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.270"
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.41.0
    hooks:
      - id: eslint
        args: [--fix]
        types_or: [css, scss, javascript]
        verbose: true
        additional_dependencies:
          - eslint
          - eslint-config-prettier
          - eslint-config-preact
          - eslint-plugin-compat
          - eslint-plugin-jest
          - eslint-plugin-react
          - eslint-plugin-react-hooks
          - "@babel/core"
          - "@babel/eslint-parser"
          - "@babel/preset-env"
          - "@babel/preset-react"
          - "@babel/plugin-syntax-class-properties"
          - "@babel/plugin-syntax-decorators"
          - "@babel/plugin-syntax-jsx"
          - jest
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        args: [--list-different, --no-semi]
        exclude: "^conf/|.*\\.html$|.*\\.json$"
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 0.11.2
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.13
    hooks:
      - id: validate-pyproject
