exclude: ".yarn/|yarn.lock"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: file-contents-sorter
        files: requirements-to-freeze.txt
  - repo: local
    hooks:
      - id: django-check
        name: django check
        entry: venv/bin/python manage.py check
        pass_filenames: false
        language: system
        always_run: true
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.11.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"]
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile=black, --lines-after-imports=2, --combine-as]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--ignore=E203,E501,W503"]
        additional_dependencies:
          - flake8-bugbear
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
    hooks:
      - id: eslint
        args: [--fix]
        types_or: [css, scss, javascript]
        verbose: true
        additional_dependencies:
          - eslint@^8.26.0
          - eslint-config-prettier
          - eslint-config-preact
          - eslint-plugin-compat
          - eslint-plugin-jest
          - eslint-plugin-react
          - eslint-plugin-react-hooks
          - "@babel/core"
          - "@babel/eslint-parser"
          - "@babel/preset-env"
          - "@babel/preset-react"
          - "@babel/plugin-syntax-class-properties"
          - "@babel/plugin-syntax-decorators"
          - "@babel/plugin-syntax-jsx"
          - jest
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        args: [--list-different, --no-semi]
        exclude: "^conf/|.*\\.html$"
