[tool.ruff]
extend-select = ["B", "E", "F", "W", "C90", "I", "N", "UP", "FBT", "C4", "DJ", "PIE", "INT", "SIM", "YTT", "G"]
extend-ignore = ["E501"]
fix = true
target-version = "py310"

[tool.ruff.isort]
combine-as-imports = true
lines-after-imports = 2

[tool.ruff.mccabe]
max-complexity = 10

[tool.coverage.run]
branch = true
omit = [
    "*migrate*",
    "*migrations*",
    "*venv*",
]

[tool.coverage.report]
skip_covered = true
show_missing = true
